# Given a sorted array (in ascending order) of integers and a target, write a function that finds the two integers that add up to the target.

# Examples:

# csSortedTwoSum([3,8,12,16], 11) -> [0,1]
# csSortedTwoSum([3,4,5], 8) -> [0,2]
# csSortedTwoSum([0,1], 1) -> [0,1]
# Notes:

# Each input will have exactly one solution.
# You may not use the same element twice.

def csSortedTwoSum(numbers, target):
    required = {}
    for i in range(len(numbers)):
        print(numbers[i])
        if target - numbers[i] in required:
            return [required[target - numbers[i]],i]
        else:
            required[numbers[i]]=i
            
#################################################

# You are given two strings, str_1 and str_2, where str_2 is generated by randomly shuffling str_1 and then adding one letter at a random position.

# Write a function that returns the letter that was added to str_2.

# Examples:

# csFindAddedLetter(str_1 = "bcde", str_2 = "bcdef") -> "f"
# csFindAddedLetter(str_1 = "", str_2 = "z") -> "z"
# csFindAddedLetter(str_1 = "b", str_2 = "bb") -> "b"
# csFindAddedLetter(str_1 = "bf", str_2 = "bfb") -> "b"
# Notes:

# str_1 and str_2 both consist of only lowercase alpha characters.

def csFindAddedLetter(str_1, str_2):
    for x in str_1:
        if x in str_2:
            str_2 = str_2.replace(x,'',1)
            print(str_2)
        else:
            print(x)
    return str_2


###############################################################

# Given a string, write a function that returns the index of the first unique (non-repeating) character. If there isn't a unique (non-repeating) character, return -1.

# Examples:

# csFirstUniqueChar(input_str = "lambdaschool") -> 2
# csFirstUniqueChar(input_str = "ilovelambdaschool") -> 0
# csFirstUniqueChar(input_str = "vvv") -> -1
# Notes:

# input_str will only contain lowercase alpha characters.

def csFirstUniqueChar(input_str):
    count = {}
    unique = []
    for x in input_str:
        if x in count:
            count[x] += 1
        else:
            count[x] = 1
    print (count)
    
    for letter in count:
        if count[letter] > 1:
            print(letter)
        else:
            unique.append(letter)
    if len(unique) > 0:
        print("hey")
        print(unique)
        if unique[0] in input_str:
            return input_str.index(unique[0])
    else:
        return -1